module.exports = {
	NOOP: 'NOOP',
	NAV_OPEN: 'NAV_OPEN',
	NAV_CLOSE: 'NAV_CLOSE',

	NOTIF_HIDE: 'NOTIF_HIDE',

	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
	MEMBER_CPASSWORD: 'MEMBER_CPASSWORD',

	SHOW_REJECT: 'SHOW_REJECT',
	REQ_ENCASH: 'REQ_ENCASH'
};